// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWG2pKYVe79ImiEcXTQpHjt8T9klDUJO0',
    appId: '1:195257230827:web:4f52331876ff49b37fe5ae',
    messagingSenderId: '195257230827',
    projectId: 'babil-iq',
    authDomain: 'babil-iq.firebaseapp.com',
    storageBucket: 'babil-iq.appspot.com',
    measurementId: 'G-XVN3DBQBMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChGSJVTWToC6bF5gZYHbZnmr5mbFbWkkQ',
    appId: '1:195257230827:android:b54bd7ce1f7d8d827fe5ae',
    messagingSenderId: '195257230827',
    projectId: 'babil-iq',
    storageBucket: 'babil-iq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6KvZX1-CT_VOYZ-94z3B1O6Ggxu-Y2Rs',
    appId: '1:195257230827:ios:47f7997cd6c3dea97fe5ae',
    messagingSenderId: '195257230827',
    projectId: 'babil-iq',
    storageBucket: 'babil-iq.appspot.com',
    iosBundleId: 'com.babylon.babylon',
  );
}
